class Urls:
    main_url = 'https://stellarburgers.nomoreparties.site'
    main_url_authorized = main_url + '/'
    create_user_url = main_url + '/api/auth/register'
    login_url = main_url + '/api/auth/login'
    delete_user = main_url + '/api/auth/user'
    create_order = main_url + '/api/orders'
    login_page_url = main_url + '/login'
    password_forgot_page = main_url + '/forgot-password'
    password_reset_page = main_url + '/reset-password'
    profile_page_url = main_url + '/account/profile'
    order_list_page = main_url + '/feed'
